weather/urls.py
from django.urls import path
from . import views

app_name = 'weather'

urlpatterns = [
    path('weather/', views.weather, name='home_weather'),
]

weather_updates/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import Home

urlpatterns = [

    path('admin/', admin.site.urls),
    path('', Home.as_view(), name='index'),
    path('weatherApp/', include('weather.urls')),
]

weather/models.py
from django.db import models

# Create your models here.

weather/views.py
from django.shortcuts import render
import requests
from bs4 import BeautifulSoup

# Create your views here.

weather_url = 'https://weather.com/en-TZ/weather/today/l/e3098160bc6bf690b70244caadff6145e27802d46872aab77148bb873c0cb43b'


def weather(request):

    # search = request.POST.get('search')
    final_url = ''
    response = requests.get(weather_url)
    data = response.text
    soup = BeautifulSoup(data, features='html.parser')
    weather_div = soup.find('div', {'id': 'LookingAhead'})
    day_part = weather_div.find_all(class_='today-daypart')
    day_title = [item.get_text() for item in weather_div.find_all(class_='today-daypart-title')]
    day_temp = [item.get_text() for item in weather_div.find_all(class_='today-daypart-temp')]
    rain_chance = [item.get_text() for item in weather_div.find_all(class_='precip-val')]
    day_desc = [item.get_text() for item in weather_div.find_all(class_='today-daypart-wxphrase')]

    more_details_div = [item.get_text() for item in weather_div.find_all(class_='dp-details')]
    final_post = []

    for (title, desc, temp, rain) in zip(day_title,day_desc, day_temp, rain_chance):
        final_post.append((title, desc, temp, rain))

    stuff_for_frontend = {
        'final': final_post
    }

    return render(request, 'weather/weather_index.html', stuff_for_frontend)

weather_updates/views.py
from django.views.generic import TemplateView


class Home(TemplateView):
    template_name = 'base.html'

templates/base.html
{% load staticfiles %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Base{% endblock title %}</title>
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <link rel="stylesheet" href="{% static 'master.css' %}">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">


</head>
<body>
<div class="container">
    <nav>
  <div class="nav-wrapper">
    <a href="" class="brand-logo">Pycon {% block tt %}Tanzania{% endblock tt %}</a>
    <ul id="nav-mobile" class="right hide-on-med-and-down">
      <li><a href="">Weather</a></li>
      <li><a href="">Weather<span class="new badge"></span></a></li>
      <li><a href="">Weather</a></li>
    </ul>
  </div>
</nav>

</div>
<div class="divider"></div>
    <div class="container">
        {% block body %}

            <div class="card">
            <div class="row">
    <div class="col s6">
      <div class="card blue-green darken-1">
        <div class="card-content white-text">
          <span class="card-title">Pycon Weather App</span>
          <i class="center-align large material-icons blue-text">filter_drama</i>
        </div>
        <div class="card-action">
          <a href="{% url 'weather:home_weather' %}">Weather Forecasting App</a>
        </div>
      </div>
    </div>
                <div class="col s6">
      <div class="card blue-green darken-1">
        <div class="card-content white-text">
          <span class="card-title">Source of Scraped data</span>
          <i class="center-align large material-icons blue-text">filter_drama</i>
        </div>
        <div class="card-action">
          <a href="https://weather.com/en-TZ/weather/today/l/e3098160bc6bf690b70244caadff6145e27802d46872aab77148bb873c0cb43b">Weather.com</a>
        </div>
      </div>
  </div>
            </div>

        {% endblock body %}
    </div>
<div class="divider"></div>

</body>
</html>
<script>
    document.addEventListener('DOMContentLoaded', function() {
    var elems = document.querySelectorAll('.collapsible');
    var instances = M.Collapsible.init(elems, options);
  });
</script>

weather/templates/weather/weather_index.html
{% extends 'base.html' %}

{% block title %}Weather{% endblock title %}
{% block tt %}Weather{% endblock tt %}
{% block body %}



    <div class="row">
    {% for post in final %}
        <div class="col s4">
            <div class="card hoverable">
                <div class="card-header">
                    <h5 class="blue-text center-align">{{ post.0 }}</h5>
                </div>
                <p class="center-align">
                    {{ post.1 }}
                </p>
                <div class="card-content">


                    <p class=""><i class="material-icons right blue-text lighten-4">wb_cloudy</i><h6 class="new badge blue lighten-5">{{ post.3 }} Rain Chance</h6> </p>
                    <p class=""><i class="material-icons right yellow-text lighten-4">wb_sunny</i><h6 class="new badge red lighten-5">{{ post.2 }} C</h6> </p>
                </div>
            </div>
        </div>

    {% endfor %}


    </div>



{% endblock body %}